// Generated by https://quicktype.io

export interface Amic {
    "АЗС 02-01": PuneHedgehog;
    "АЗС 02-02": PuneHedgehog;
    "АЗС 02-04": PuneHedgehog;
    "АЗС 03-01": PuneHedgehog;
    "АЗС 03-02": PuneHedgehog;
    "АЗС 03-03": PuneHedgehog;
    "АЗС 03-04": PuneHedgehog;
    "АЗС 03-05": PuneHedgehog;
    "АЗС 03-07": PuneHedgehog;
    "АЗС 03-09": PuneHedgehog;
    "АЗС 03-10": PuneHedgehog;
    "АЗС 03-11": PuneHedgehog;
    "АЗС 04-01": PuneHedgehog;
    "АЗС 04-03": PuneHedgehog;
    "АЗС 04-12": PuneHedgehog;
    "АЗС 04-13": PuneHedgehog;
    "АЗС 04-14": PuneHedgehog;
    "АЗС 04-16": PuneHedgehog;
    "АЗС 04-17": PuneHedgehog;
    "АЗС 04-19": PuneHedgehog;
    "АЗС 06-03": PuneHedgehog;
    "АЗС 06-04": PuneHedgehog;
    "АЗС 06-05": PuneHedgehog;
    "АЗС 06-06": PuneHedgehog;
    "АЗС 06-07": PuneHedgehog;
    "АЗС 07-01": АЗС0701_Class;
    "АЗС 07-02": PuneHedgehog;
    "АЗС 07-04": PuneHedgehog;
    "АЗС 07-05": PuneHedgehog;
    "АЗС 07-06": PuneHedgehog;
    "АЗС 07-07": PuneHedgehog;
    "АЗС 07-08": PuneHedgehog;
    "АЗС 08-04": PuneHedgehog;
    "АЗС 08-07": PuneHedgehog;
    "АЗС 08-10": PuneHedgehog;
    "АЗС 09-01": PuneHedgehog;
    "АЗС 09-02": PuneHedgehog;
    "АЗС 09-05": PuneHedgehog;
    "АЗС 09-08": PuneHedgehog;
    "АЗС 09-09": PuneHedgehog;
    "АЗС 10-02": PuneHedgehog;
    "АЗС 10-03": PuneHedgehog;
    "АЗС 10-04": АЗС0701_Class;
    "АЗС 10-05": PuneHedgehog;
    "АЗС 10-06": PuneHedgehog;
    "АЗС 10-08": PuneHedgehog;
    "АЗС 10-10": АЗС0701_Class;
    "АЗС 10-11": PuneHedgehog;
    "АЗС 10-12": PuneHedgehog;
    "АЗС 10-13": PuneHedgehog;
    "АЗС 10-15": PuneHedgehog;
    "АЗС 10-16": PuneHedgehog;
    "АЗС 10-17": PuneHedgehog;
    "АЗС 10-21": Азс1;
    "АЗС 10-22": PuneHedgehog;
    "АЗС 10-23": PuneHedgehog;
    "АЗС 11-01": Азс1101;
    "АЗС 11-02": PuneHedgehog;
    "АЗС 11-03": АЗС0701_Class;
    "АЗС 11-07": PuneHedgehog;
    "АЗС 11-09": PuneHedgehog;
    "АЗС 11-10": PuneHedgehog;
    "АЗС 11-11": PuneHedgehog;
    "АЗС 11-12": PuneHedgehog;
    "АЗС 11-13": PuneHedgehog;
    "АЗС 11-14": PuneHedgehog;
    "АЗС 11-15": PuneHedgehog;
    "АЗС 11-16": PuneHedgehog;
    "АЗС 11-17": PuneHedgehog;
    "АЗС 11-18": PuneHedgehog;
    "АЗС 11-20": PuneHedgehog;
    "АЗС 11-21": PuneHedgehog;
    "АЗС 11-22": PuneHedgehog;
    "АЗС 11-23": PuneHedgehog;
    "АЗС 11-24": PuneHedgehog;
    "АЗС 11-25": PuneHedgehog;
    "АЗС 11-26": PuneHedgehog;
    "АЗС 11-28": PuneHedgehog;
    "АЗС 11-29": PuneHedgehog;
    "АЗС 11-30": PuneHedgehog;
    "АЗС 12-01": PuneHedgehog;
    "АЗС 12-03": PuneHedgehog;
    "АЗС 12-04": PuneHedgehog;
    "АЗС 12-08": Азс1;
    "АЗС 12-09": PuneHedgehog;
    "АЗС 12-10": PuneHedgehog;
    "АЗС 12-11": PuneHedgehog;
    "АЗС 14-01": АЗС0701_Class;
    "АЗС 14-03": PuneHedgehog;
    "АЗС 14-04": PuneHedgehog;
    "АЗС 14-05": PuneHedgehog;
    "АЗС 14-06": PuneHedgehog;
    "АЗС 14-08": АЗС0701_Class;
    "АЗС 14-09": PuneHedgehog;
    "АЗС 14-10": PuneHedgehog;
    "АЗС 14-11": PuneHedgehog;
    "АЗС 14-12": PuneHedgehog;
    "АЗС 14-13": PuneHedgehog;
    "АЗС 14-14": PuneHedgehog;
    "АЗС 14-15": PuneHedgehog;
    "АЗС 14-17": PuneHedgehog;
    "АЗС 14-18": АЗС0701_Class;
    "АЗС 15-01": АЗС0701_Class;
    "АЗС 15-04": Азс1504;
    "АЗС 15-05": PuneHedgehog;
    "АЗС 15-06": PuneHedgehog;
    "АЗС 15-07": АЗС0701_Class;
    "АЗС 15-08": АЗС0701_Class;
    "АЗС 15-09": PuneHedgehog;
    "АЗС 16-03": АЗС1603_Class;
    "АЗС 16-06": PuneHedgehog;
    "АЗС 16-07": PuneHedgehog;
    "АЗС 16-09": PuneHedgehog;
    "АЗС 16-11": PuneHedgehog;
    "АЗС 16-12": PuneHedgehog;
    "АЗС 16-13": АЗС0701_Class;
    "АЗС 16-15": PuneHedgehog;
    "АЗС 16-18": PuneHedgehog;
    "АЗС 16-19": PuneHedgehog;
    "АЗС 16-20": PuneHedgehog;
    "АЗС 16-21": АЗС1603_Class;
    "АЗС 16-25": PuneHedgehog;
    "АЗС 16-27": АЗС0701_Class;
    "АЗС 16-28": АЗС1603_Class;
    "АЗС 16-31": АЗС1603_Class;
    "АЗС 16-38": PuneHedgehog;
    "АЗС 16-40": PuneHedgehog;
    "АЗС 16-41": АЗС1603_Class;
    "АЗС 16-44": PuneHedgehog;
    "АЗС 16-45": PuneHedgehog;
    "АЗС 16-46": PuneHedgehog;
    "АЗС 16-47": PuneHedgehog;
    "АЗС 16-49": PuneHedgehog;
    "АЗС 16-50": PuneHedgehog;
    "АЗС 17-02": Азс1;
    "АЗС 17-03": PuneHedgehog;
    "АЗС 17-04": PuneHedgehog;
    "АЗС 17-06": PuneHedgehog;
    "АЗС 17-07": PuneHedgehog;
    "АЗС 18-01": PuneHedgehog;
    "АЗС 18-02": PuneHedgehog;
    "АЗС 18-03": PuneHedgehog;
    "АЗС 18-04": PuneHedgehog;
    "АЗС 18-05": PuneHedgehog;
    "АЗС 18-06": PuneHedgehog;
    "АЗС 19-01": PuneHedgehog;
    "АЗС 19-02": PuneHedgehog;
    "АЗС 20-01": АЗС0701_Class;
    "АЗС 20-04": PuneHedgehog;
    "АЗС 21-01": PuneHedgehog;
    "АЗС 21-03": PuneHedgehog;
    "АЗС 21-04": PuneHedgehog;
    "АЗС 21-05": PuneHedgehog;
    "АЗС 23-01": PuneHedgehog;
    "АЗС 23-04": PuneHedgehog;
    "АЗС 23-05": PuneHedgehog;
    "АЗС 23-06": PuneHedgehog;
    "АЗС 23-07": PuneHedgehog;
    "АЗС 24-01": PuneHedgehog;
    "АЗС 24-02": PuneHedgehog;
    "АЗС 24-03": PuneHedgehog;
    "АЗС 24-06": АЗС1603_Class;
    "АЗС 24-08": PuneHedgehog;
    "АЗС 24-09": PuneHedgehog;
    "АЗС 24-10": PuneHedgehog;
    "АЗС 24-12": PuneHedgehog;
    "АЗС 24-13": PuneHedgehog;
    "АЗС 24-14": PuneHedgehog;
    "АЗС 24-15": PuneHedgehog;
    "АЗС 24-16": PuneHedgehog;
    "АЗС 25-04": PuneHedgehog;
    "АЗС 26-01": PuneHedgehog;
    "АЗС 26-02": PuneHedgehog;
    "АЗС 26-03": АЗС0701_Class;
    "АЗС 26-04": PuneHedgehog;
    "АЗС 26-05": АЗС0701_Class;
    "АЗС 26-06": PuneHedgehog;
}

export interface PuneHedgehog {
    address:           string;
    lat:               string;
    lng:               string;
    icons:             { [key: string]: Icon | null };
    services_img_data: { [key: string]: ServicesImgDatum };
}

export enum Icon {
    AdbluePNG = "adblue.png",
    The559Ef35B1485FSVG = "559ef35b1485f.svg",
    The559Ef36876F9FSVG = "559ef36876f9f.svg",
    The559Ef36F6A220SVG = "559ef36f6a220.svg",
    The559Ef376A139CSVG = "559ef376a139c.svg",
    The559Ef37Ce9DdcSVG = "559ef37ce9ddc.svg",
    The559Ef385E596BSVG = "559ef385e596b.svg",
}

export enum ServicesImgDatum {
    Empty = "",
    HotdogSVG = "hotdog.svg",
    The559Ef3D049F44SVG = "559ef3d049f44.svg",
    The559Ef3De194EdSVG = "559ef3de194ed.svg",
    The559Ef3F506C53SVG = "559ef3f506c53.svg",
    The559Ef3Fcd5590SVG = "559ef3fcd5590.svg",
    The559Ef40E2985CSVG = "559ef40e2985c.svg",
    The559Ef42A77E9ESVG = "559ef42a77e9e.svg",
    The559Ef42Fb61BdSVG = "559ef42fb61bd.svg",
    The559Ef46146DbbSVG = "559ef46146dbb.svg",
    The559Ef4728F362SVG = "559ef4728f362.svg",
    The559Ef47C079E8SVG = "559ef47c079e8.svg",
}

export interface АЗС0701_Class {
    address:           string;
    lat:               string;
    lng:               string;
    icons:             { [key: string]: Icon };
    services_img_data: { [key: string]: ServicesImgDatum };
}

export interface Азс1 {
    address:           string;
    lat:               string;
    lng:               string;
    icons:             { [key: string]: Icon | null };
    services_img_data: АЗС1021_ServicesImgData;
}

export interface АЗС1021_ServicesImgData {
    "": null;
}

export interface Азс1101 {
    address:           string;
    lat:               string;
    lng:               string;
    icons:             Icons;
    services_img_data: { [key: string]: ServicesImgDatum };
}

export interface Icons {
    "ДП Prem": Icon;
    "95 Prem": Icon;
}

export interface Азс1504 {
    address:           string;
    lat:               string;
    lng:               string;
    icons:             { [key: string]: Icon | null };
    services_img_data: АЗС1504_ServicesImgData;
}

export interface АЗС1504_ServicesImgData {
    Кіоск: string;
}

export interface АЗС1603_Class {
    address:           string;
    lat:               string;
    lng:               string;
    icons:             { [key: string]: Icon };
    services_img_data: АЗС1021_ServicesImgData;
}
