// Generated by https://quicktype.io

export interface Brsm {
    fuel_types: FuelTypes;
    services?:   Services; // info about services, not necessary for fuel availability
    points:    Point;
}

export interface FuelTypes {
    items: FuelTypesItem[];
}

export interface FuelTypesItem {
    id:       number;
    name:     string;
    data:     Data;
    image:    string;
    weight:   number;
    bg_color: string;
}

export interface Data {
    term_id:          number;
    name:             string;
    slug:             string;
    term_group:       number;
    term_taxonomy_id: number;
    taxonomy:         Taxonomy;
    description:      string;
    parent:           number;
    count:            number;
    filter:           Filter;
}

export enum Filter {
    Raw = "raw",
}

export enum Taxonomy {
    FuelType = "fuel_type",
    MapPointService = "map_point_service",
    MapRegion = "map_region",
}

export interface Services {
    items:   RegionElement[];
    regions: RegionElement[];
}

export interface RegionElement {
    id:    number;
    name:  string;
    data:  Data;
    icon?: string;
}

export interface Point {
    items: PointItem[];
}

export interface PointItem {
    id:          number;
    lat:         number;
    lng:         number;
    services:    number[];
    gps:         string;
    region:      number;
    person_name: null | string;
    phone:       string;
    fuel_types:  number[];
    title:       string;
}
