// Generated by https://quicktype.io

export interface Brsm {
    get_map_fuel_types: GetMapFuelTypes;
    get_map_services:   GetMapServices;
    get_maps_points:    GetMapsPoints;
}

export interface GetMapFuelTypes {
    items: GetMapFuelTypesItem[];
}

export interface GetMapFuelTypesItem {
    id:       number;
    name:     string;
    data:     Data;
    image:    string;
    weight:   number;
    bg_color: string;
}

export interface Data {
    term_id:          number;
    name:             string;
    slug:             string;
    term_group:       number;
    term_taxonomy_id: number;
    taxonomy:         Taxonomy;
    description:      string;
    parent:           number;
    count:            number;
    filter:           Filter;
}

export enum Filter {
    Raw = "raw",
}

export enum Taxonomy {
    FuelType = "fuel_type",
    MapPointService = "map_point_service",
    MapRegion = "map_region",
}

export interface GetMapServices {
    items:   RegionElement[];
    regions: RegionElement[];
}

export interface RegionElement {
    id:    number;
    name:  string;
    data:  Data;
    icon?: string;
}

export interface GetMapsPoints {
    items: GetMapsPointsItem[];
}

export interface GetMapsPointsItem {
    id:          number;
    lat:         number;
    lng:         number;
    services:    number[];
    gps:         string;
    region:      number;
    person_name: null | string;
    phone:       string;
    fuel_types:  number[];
    title:       string;
}
