// Generated by https://quicktype.io

export interface Chipo {
    KOObject:                     KOObject[];
    pluginurl:                    string;
    defaultSearchMessage:         null;
    defaultSearchLocationMessage: string;
    disableInfoBoxes:             string;
    distanceWithinText:           string;
    distanceOfText:               string;
    hideviewdetailbuttons:        string;
    measurementUnits:             string;
    measurementUnitsMetricText:   string;
    measurementUnitsImperialText: string;
    noSelectedTypeMessage:        string;
    noTypeMessage:                string;
    noFilesFoundMessage:          string;
    noGeoSupported:               string;
    printDirectionsMessage:       string;
    viewLocationDetail:           string;
}

export interface KOObject {
    id:           number;
    locations:    Location[];
    homelocation: null;
    categories:   Category[];
    options:      Options;
}

export interface Category {
    title:       Title;
    slug:        Slug;
    selected:    null;
    markerImage: null;
    sortIndex:   null;
}

export enum Slug {
    Uk = "uk",
}

export enum Title {
    Українською = "Українською",
}

export interface Location {
    title:              string;
    cssClass:           string;
    description:        string;
    simpledescription:  string;
    dateCreated:        null;
    categories:         Category[];
    customCategories:   null;
    latitude:           string;
    longitude:          string;
    address:            Address;
    pinImageUrl:        string;
    pinShadowImageUrl:  string;
    pinShadowOverrides: null;
    pinShape:           null;
    imageUrl:           null;
    smallImageUrl:      null;
    locationUrl:        string;
    _mapMarker:         string;
    expanded:           null;
    pinColor:           string;
}

export enum Address {
    Empty = "",
    PН13ТуркаЛьвівськаОбластьУкраїна82500P = "<p>Н13, Турка, Львівська область, Україна, 82500</p>\n",
}

export interface Options {
    categoriesaslist:            string;
    categoriesticked:            string;
    categoriesmultiselect:       boolean;
    categoriesmatchall:          boolean;
    clustermarkers:              string;
    clustermaxzoomlevel:         string;
    clustergridsize:             string;
    country:                     string;
    customstylers:               string;
    defaultzoom:                 string;
    defaultdirectionsmode:       string;
    disablescroll:               boolean;
    expandsingleresult:          boolean;
    fullpageviewenabled:         string;
    geoenabled:                  string;
    hideaddress:                 boolean;
    hidecategoriesonitems:       string;
    hideviewdetailbuttons:       string;
    hideinfowindow:              boolean;
    hideuntilsearch:             boolean;
    hidefilter:                  string;
    initiallyselectedcategories: string;
    initialmaptype:              string;
    initialsorttype:             string;
    infoboxparts:                string[];
    infoheight:                  number;
    infowidth:                   number;
    keepzoomlevel:               boolean;
    limitresults:                number;
    locationsperpage:            string;
    locationstoshow:             string;
    menushideonselect:           boolean;
    openinnew:                   boolean;
    orderby:                     string;
    orderdir:                    string;
    simplesearch:                string;
    singlelocationzoom:          number;
    showdirections:              string;
    selectedzoomlevel:           string;
    startlat:                    string;
    startlong:                   string;
    streetview:                  boolean | string;
    searchdistances:             string[];
    viewstyle:                   string;
}
