// Generated by https://quicktype.io

export interface WogStation {
    data: Data;
}

export interface Data {
    service_filters:         ServiceFilter[];
    fuel_filters:            FuelFilter[];
    applied_service_filters: any[];
    applied_fuel_filters:    any[];
    stations:                Station[];
}

export interface FuelFilter {
    price:  number;
    cla:    string;
    brand?: string;
    name:   string;
    id:     number;
}

export interface ServiceFilter {
    icon: string;
    name: string;
    id:   number;
}

export interface Station {
    link:        string;
    city?:       string;
    coordinates: Coordinates;
    name:        string;
    id:          number;
}

export interface Coordinates {
    longitude: number;
    latitude:  number;
}
