// Generated by https://quicktype.io

export interface Motto {
    markers: Markers;
}

export interface Markers {
    marker: Marker[]
    // marker: { [key: string]: string }[];
}

export interface Marker {
    id: string;
    idvn: string;
    name: string;
    idobl: string;
    toplivo: string;
    magaz: string;
    kiosk: string;
    cafe: string;
    shinm: string;
    moyka: string;
    address: string;
    lat: string;
    lng: string;
    type: string;
    link: string;
    'self-closing': string;
}

/**
    {
        "-id": "1",
        "-idvn": "0201",
        "-name": "АЗС Motto",
        "-idobl": "0",
        "-toplivo": "Види пального: А95 EURO, А95, А95 Premium, А92 Euro, ДП Euro, ДП, Газ",
        "-magaz": "+",
        "-kiosk": "",
        "-cafe": "+",
        "-shinm": "",
        "-moyka": "+",
        "-address": "Київська обл., м. Київ, вул. Богатирська, будинок 3-Д, (літ. XXXIV)",
        "-lat": "50.495398",
        "-lng": "30.490349",
        "-type": "azs",
        "-link": "https://www.google.com.ua/maps/place/50.495398,30.490349",
        "-self-closing": "true"
    },
 * 
 * 
 */