// Generated by https://quicktype.io

export interface Shell {
    id:                                string;
    type:                              number;
    brand:                             Brand;
    name:                              string;
    lat:                               number;
    lng:                               number;
    country_code:                      CountryCode;
    address:                           string;
    city:                              string;
    state:                             State;
    postcode:                          string;
    telephone:                         string;
    country:                           Country;
    amenities:                         string[];
    inactive:                          boolean;
    distance:                          number;
    driving_distance:                  null;
    driving_duration:                  null;
    website_url:                       string;
    open_status:                       OpenStatus;
    next_open_status_change:           null | string;
    tz_offset:                         number;
    fuels:                             Fuel[];
    next_forecourt_open_status_change: null | string;
    next_shop_open_status_change:      null;
    forecourt_open_status:             OpenStatus;
    shop_open_status:                  OpenStatus;
}

export enum Brand {
    Shell = "shell",
}

export enum Country {
    Poland = "Poland",
    Ukraine = "Ukraine",
}

export enum CountryCode {
    Pl = "PL",
    Ua = "UA",
}

export enum OpenStatus {
    Closed = "closed",
    TwentyFourHour = "twenty_four_hour",
    Unknown = "unknown",
}

export enum Fuel {
    AutogasLpg = "autogas_lpg",
    ElectricChargingOther = "electric_charging_other",
    FuelsaveMidgradeGasoline = "fuelsave_midgrade_gasoline",
    FuelsaveRegularDiesel = "fuelsave_regular_diesel",
    LowOctaneGasoline = "low_octane_gasoline",
    MidgradeGasoline = "midgrade_gasoline",
    PremiumDiesel = "premium_diesel",
    PremiumGasoline = "premium_gasoline",
    ShellRegularDiesel = "shell_regular_diesel",
    SuperPremiumGasoline = "super_premium_gasoline",
    TruckDiesel = "truck_diesel",
}

export enum State {
    Empty = "",
    WojLubelskie = "Woj. lubelskie",
    WojPodkarpackie = "Woj. podkarpackie",
}
