// Generated by https://quicktype.io

export interface SocarStations {
    data:  Datum[];
    links: Links;
}

export interface Datum {
    id:         string;
    type:       Type;
    attributes: Attributes;
}

export interface Attributes {
    title:       string;
    address:     string;
    tel:         string;
    city_slug:   CitySlug;
    street_slug: string;
    marker:      Marker;
    fuelPrices:  FuelPrice[];
    services:    Service[];
}

export enum CitySlug {
    Empty = "",
    Oddesa = "oddesa",
    Odessa = "odessa",
}

export interface FuelPrice {
    // AdBlue3190 = "AdBlue (31.90)",
    // AdBlue3299 = "AdBlue (32.99)",
    // DieselNanoExtro000 = "Diesel Nano Extro (0.00)",
    // DieselNanoExtro5799 = "Diesel Nano Extro (57.99)",
    // Lpg4198 = "LPG (41.98)",
    // Nano955199 = "NANO 95 (51.99)",
    // NanoДп5699 = "NANO ДП (56.99)",
    limit: string;
    name: string;
    price: string;
}

export interface Marker {
    lat: number;
    lng: number;
}

export enum Service {
    BusinessCorner = "Business corner",
    ButaMarket = "Buta Market",
    SOCARPay = "SOCAR Pay",
    WCДляОсібЗІнвалідністю = "WC для осіб з інвалідністю",
    Wc = "WC",
    WiFi = "Wi-Fi",
    АвтоматичнаЧисткаВзуття = "Автоматична чистка взуття",
    ВинісТермінала = "Виніс термінала",
    ДитячеКрісло = "Дитяче крісло",
    ДоставкаBoltFood = "Доставка Bolt Food",
    ДоставкаGlovo = "Доставка Glovo",
    ЕлектроннаЧерга = "Електронна черга",
    ЗарядкаДляСмартфонiв = "Зарядка для смартфонiв",
    КаваНапої = "Кава/напої",
    КарткиSCard = "Картки sCard",
    ЛітняТераса = "Літня тераса",
    МийкаАвто = "Мийка авто",
    ОбмінВалют = "Обмін валют",
    Парковка = "Парковка",
    ПарковкаTIR = "Парковка TIR",
    ПеленальнийСтолик = "Пеленальний столик",
    Пилосос = "Пилосос",
    ПлатіжнийТермінал = "Платіжний термінал",
    ПовноціннаКухня = "Повноцінна кухня",
    ПоштоматНоваПошта = "Поштомат Нова Пошта",
    ПідкачкаШин = "Підкачка шин",
    РозкладАвіаРейсів = "Розклад авіа-рейсів",
    Телефон = "Телефон",
    ШвидкіснаПРКTIR = "Швидкісна ПРК TIR",
}

export enum Type {
    Stations = "stations",
}

export interface Links {
    self:   string;
    client: string;
}
